services:
  ddns-updater:
    image: ghcr.io/qdm12/ddns-updater
    container_name: ddns-updater
    networks:
      - traefik-public
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIC_HTTP_PROVIDERS=all
      - PUBLICIPV4_PROVIDERS=all
      - PUBLICIPV6_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMOUT=3s
      - HTTP_TIMOUT=10s
      - RESOLVER_ADDRESS=192.168.5.76

      # Web UI
      - LISTENING_ADDRESS=:8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # '0' = disable
      - BACKUP_DIRECTORY=/updater/data

      # Logs
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
    restart: unless-stopped
    labels:
      - "ddns-updater.skip=true" # Prevent Komodo from stopping with StopAllContainers
      - "traefik.enable=true"
      - "traefik.http.routers.ddns-updater.entrypoints=http"
      - "traefik.http.routers.ddns-updater.rule=Host(`ddns.local.serbicki.com`)"
      - "traefik.docker.network=traefik-public"
      # - "traefik.http.services.ddns-updater.loadbalancer.server.port=80"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ddns-updater.middlewares=traefik-https-redirect"
      - "traefik.http.routers.ddns-updater-secure.entrypoints=https"
      - "traefik.http.routers.ddns-updater-secure.rule=Host(`ddns.local.serbicki.com`)"
      - "traefik.http.routers.ddns-updater-secure.tls=true"
      - "traefik.http.routers.ddns-updater-secure.tls.certresolver=letsencrypt"

networks:
  traefik-public:
    external: true
